// https://openweathermap.org/api/air-pollution

import { fetchData } from './api';
import { City, CountryCode } from './types';

type DirectResponse = City[];

export const sampleDirectResponse: DirectResponse = [
  {
    name: 'London',
    local_names: {
      ku: 'London',
      mk: 'Лондон',
      de: 'London',
      mr: 'लंडन',
      tl: 'Londres',
      kl: 'London',
      br: 'Londrez',
      lo: 'ລອນດອນ',
      ug: 'لوندۇن',
      mg: 'Lôndôna',
      tr: 'Londra',
      kv: 'Лондон',
      bm: 'London',
      to: 'Lonitoni',
      mt: 'Londra',
      os: 'Лондон',
      ka: 'ლონდონი',
      ca: 'Londres',
      ko: '런던',
      yi: 'לאנדאן',
      st: 'London',
      th: 'ลอนดอน',
      bh: 'लंदन',
      ha: 'Landan',
      am: 'ለንደን',
      gu: 'લંડન',
      sd: 'لنڊن',
      vi: 'Luân Đôn',
      ascii: 'London',
      tk: 'London',
      az: 'London',
      es: 'Londres',
      eo: 'Londono',
      sk: 'Londýn',
      fj: 'Lodoni',
      el: 'Λονδίνο',
      ht: 'Lonn',
      ur: 'علاقہ لندن',
      ba: 'Лондон',
      qu: 'London',
      kk: 'Лондон',
      sr: 'Лондон',
      he: 'לונדון',
      nn: 'London',
      hy: 'Լոնդոն',
      ta: 'இலண்டன்',
      ay: 'London',
      su: 'London',
      ln: 'Lóndɛlɛ',
      ig: 'London',
      bs: 'London',
      zh: '伦敦',
      vo: 'London',
      id: 'London',
      sl: 'London',
      wo: 'Londar',
      gl: 'Londres',
      kn: 'ಲಂಡನ್',
      ff: 'London',
      ms: 'London',
      te: 'లండన్',
      io: 'London',
      ar: 'لندن',
      af: 'Londen',
      bi: 'London',
      tt: 'Лондон',
      mi: 'Rānana',
      av: 'Лондон',
      wa: 'Londe',
      ky: 'Лондон',
      gd: 'Lunnainn',
      uk: 'Лондон',
      fr: 'Londres',
      bn: 'লন্ডন',
      fi: 'Lontoo',
      ny: 'London',
      lt: 'Londonas',
      zu: 'ILondon',
      or: 'ଲଣ୍ଡନ',
      ie: 'London',
      ro: 'Londra',
      gv: 'Lunnin',
      fo: 'London',
      ml: 'ലണ്ടൻ',
      cv: 'Лондон',
      ee: 'London',
      li: 'Londe',
      co: 'Londra',
      feature_name: 'London',
      et: 'London',
      tg: 'Лондон',
      sh: 'London',
      nv: 'Tooh Dineʼé Bikin Haalʼá',
      ps: 'لندن',
      is: 'London',
      om: 'Landan',
      hu: 'London',
      no: 'London',
      fa: 'لندن',
      uz: 'London',
      bg: 'Лондон',
      ne: 'लन्डन',
      km: 'ឡុងដ៍',
      be: 'Лондан',
      ga: 'Londain',
      ab: 'Лондон',
      da: 'London',
      pl: 'Londyn',
      cu: 'Лондонъ',
      sm: 'Lonetona',
      gn: 'Lóndyre',
      sv: 'London',
      it: 'Londra',
      tw: 'London',
      sw: 'London',
      en: 'London',
      ru: 'Лондон',
      kw: 'Loundres',
      oc: 'Londres',
      pt: 'Londres',
      fy: 'Londen',
      sa: 'लन्डन्',
      na: 'London',
      lb: 'London',
      ja: 'ロンドン',
      cs: 'Londýn',
      cy: 'Llundain',
      hr: 'London',
      si: 'ලන්ඩන්',
      ia: 'London',
      hi: 'लंदन',
      yo: 'Lọndọnu',
      nl: 'Londen',
      jv: 'London',
      sc: 'Londra',
      my: 'လန်ဒန်မြို့',
      eu: 'Londres',
      mn: 'Лондон',
      rm: 'Londra',
      ce: 'Лондон',
      an: 'Londres',
      bo: 'ལོན་ཊོན།',
      pa: 'ਲੰਡਨ',
      se: 'London',
      lv: 'Londona',
      sq: 'Londra',
      sn: 'London',
      so: 'London',
    },
    lat: 51.5073219,
    lon: -0.1276474,
    country: 'GB',
    state: 'England',
  },
  {
    name: 'City of London',
    local_names: {
      ur: 'لندن شہر',
      uk: 'Лондонське Сіті',
      en: 'City of London',
      pt: 'Cidade de Londres',
      hi: 'सिटी ऑफ़ लंदन',
      ko: '시티 오브 런던',
      es: 'City de Londres',
      fr: 'Cité de Londres',
      ru: 'Сити',
      lt: 'Londono Sitis',
      he: 'הסיטי של לונדון',
      zh: '倫敦市',
    },
    lat: 51.5156177,
    lon: -0.0919983,
    country: 'GB',
    state: 'England',
  },
  {
    name: 'London',
    local_names: {
      yi: 'לאנדאן',
      oj: 'Baketigweyaang',
      lv: 'Landona',
      en: 'London',
      be: 'Лондан',
      he: 'לונדון',
      hy: 'Լոնտոն',
      ga: 'Londain',
      ka: 'ლონდონი',
      cr: 'ᓬᐊᐣᑕᐣ',
      ar: 'لندن',
      lt: 'Londonas',
      th: 'ลอนดอน',
      el: 'Λόντον',
      ru: 'Лондон',
      ja: 'ロンドン',
      fr: 'London',
      ug: 'لوندۇن',
      bn: 'লন্ডন',
      iu: 'ᓚᓐᑕᓐ',
      fa: 'لندن',
      ko: '런던',
    },
    lat: 42.9832406,
    lon: -81.243372,
    country: 'CA',
    state: 'Ontario',
  },
  {
    name: 'Chelsea',
    local_names: {
      ur: 'چیلسی، لندن',
      id: 'Chelsea, London',
      ru: 'Челси',
      ja: 'チェルシー',
      uk: 'Челсі',
      hi: 'चेल्सी, लंदन',
      sv: 'Chelsea, London',
      he: "צ'לסי",
      pt: 'Chelsea',
      hu: 'Chelsea',
      fa: 'چلسی',
      tr: 'Chelsea, Londra',
      sh: 'Chelsea, London',
      az: 'Çelsi',
      af: 'Chelsea, Londen',
      ga: 'Chelsea',
      et: 'Chelsea',
      zh: '車路士',
      es: 'Chelsea',
      ar: 'تشيلسي',
      de: 'Chelsea',
      el: 'Τσέλσι',
      sk: 'Chelsea',
      en: 'Chelsea',
      pl: 'Chelsea',
      ko: '첼시',
      it: 'Chelsea',
      da: 'Chelsea',
      eu: 'Chelsea',
      nl: 'Chelsea',
      no: 'Chelsea',
      vi: 'Chelsea, Luân Đôn',
      fr: 'Chelsea',
    },
    lat: 51.4875167,
    lon: -0.1687007,
    country: 'GB',
    state: 'England',
  },
  {
    name: 'London',
    lat: 37.1289771,
    lon: -84.0832646,
    country: 'US',
    state: 'Kentucky',
  },
];

export async function fetchDirect(
  city: string,
  state?: string,
  country?: string,
  limit?: number,
) {
  const q = [city, state, country].filter(Boolean).join(',');
  return fetchData<DirectResponse>(
    `http://api.openweathermap.org/geo/1.0/direct?q=${q}&limit=${limit}`,
  );
}

type ZipResponse = {
  zip: string;
  name: string;
  lat: number;
  lon: number;
  country: CountryCode;
};

export const sampleZipResponse: ZipResponse = {
  zip: 'E14',
  name: 'London',
  lat: 51.4969,
  lon: -0.0087,
  country: 'GB',
};

export async function fetchZip(zipCode: string, countryCode: string) {
  return fetchData<ZipResponse>(
    `http://api.openweathermap.org/geo/1.0/zip?zip=${zipCode},${countryCode}`,
  );
}

type ReverseResponse = City[];

export const sampleReverseResponse: ReverseResponse = [
  {
    name: 'City of Westminster',
    local_names: {
      he: 'וסטמינסטר',
      en: 'City of Westminster',
      mk: 'Град Вестминстер',
      be: 'Вэстмінстэр',
      ru: 'Вестминстер',
      fr: 'Cité de Westminster',
      cy: 'San Steffan',
      ko: '시티오브웨스트민스터',
    },
    lat: 51.4973206,
    lon: -0.137149,
    country: 'GB',
    state: 'England',
  },
];

export async function fetchReveerse(lat: number, lon: number, limit: number) {
  return fetchData<ReverseResponse>(
    `http://api.openweathermap.org/geo/1.0/reverse?lat={lat}&lon=${lon}&limit=${limit}`,
  );
}
